/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cyclify;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MAHE
 */
public class OAddCycle extends javax.swing.JFrame {
    static long OID;

    /**
     * Creates new form OAddCycle
     */
    public OAddCycle(long a) {
        OID = a;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button7 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cycleidfield = new javax.swing.JTextField();
        makefield = new javax.swing.JTextField();
        colourfield = new javax.swing.JTextField();
        ratefield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gngfield = new javax.swing.JComboBox<>();
        backbutton = new javax.swing.JButton();
        submitbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        yopfield = new javax.swing.JTextField();
        monthmenu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        button7.setLabel("Go Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cycle ID : ");

        jLabel2.setText("Make :");

        month.setText("Month of Purchase :");

        jLabel4.setText("Colour :");

        cycleidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cycleidfieldActionPerformed(evt);
            }
        });

        makefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makefieldActionPerformed(evt);
            }
        });

        colourfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourfieldActionPerformed(evt);
            }
        });

        ratefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratefieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Rate per hour : ");

        jLabel6.setText("Gear system : ");

        gngfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geared", "Not Geared" }));
        gngfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gngfieldActionPerformed(evt);
            }
        });

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Enter the details of your cycle  :");

        year.setText("Year of Purchase (YYYY) :");

        monthmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthmenuActionPerformed(evt);
            }
        });

        jLabel3.setText("₹");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(submitbutton))
                    .addComponent(jLabel1)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backbutton)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cycleidfield))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(monthmenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(makefield)
                                    .addComponent(colourfield)
                                    .addComponent(ratefield)
                                    .addComponent(gngfield, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yopfield, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cycleidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(colourfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ratefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(gngfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year)
                    .addComponent(yopfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbutton)
                    .addComponent(backbutton))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cycleidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cycleidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cycleidfieldActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
    Owner1 ob = new Owner1(OID);
    ob.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
     try{
            
            
        String CID=cycleidfield.getText();
        String Make = makefield.getText();
        String Color = colourfield.getText();
        Integer rate = Integer.parseInt(ratefield.getText());
        Integer yop=Integer.parseInt(yopfield.getText()); Integer m1=0;
        String mop = monthmenu.getItemAt(monthmenu.getSelectedIndex());
        String gearstr =  gngfield.getItemAt(gngfield.getSelectedIndex());
        
        int gearint;
        if(gearstr=="Geared")
            gearint=1;
        else
            gearint=0;
        
        
        switch(      mop              )
            {   
                case "January":
                    m1=1;
                    
                    
                    break;
                    
                case "February":
                    m1=2;
                    
                    break;
                case "March":
                    m1= 3;
                    
                    break;
                case "April":
                    m1=4;
                    
                    break;
                case "May":
                    m1=5;
                    
                    break;
                case "June":
                    m1=6;
                    
                    break;
                case "July":
                    m1= 7;
                    
                    break;

                    
                case "August":
                    m1=8;
                    
                    
                    break;
                case "September":
                    m1= 9;
                    
                    break;
                case "October":
                    m1= 10;
                    
                    break;
                case "November":
                    m1= 11;
                    
                    
                    break;
                case "December":
                    m1= 12;
                    
                    break;

                
            }
        m1=(m1*100)+(yop-2000);

        
        
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost", "system", "prajant");
        Statement stmt = con.createStatement();
        stmt.executeQuery("insert into cycles values ('"  +  CID  +  "','" + Make + "','"  + Color  +  "',"  +  m1  +  "," + gearint + "," + rate + "," + OID + ")");
        
        
        con.close();
        
        JOptionPane.showMessageDialog(null,"Cycle Added", "Success",JOptionPane.INFORMATION_MESSAGE);
        
        
        Owner1 ab = new Owner1(OID);
        ab.setVisible(true);
        this.setVisible(false);
        
        
        }
        
        
        catch (SQLException ex) 
        {
            System.out.println(ex);
        }
        catch (ClassNotFoundException ex) 
        {

            System.out.println(ex);			
        }
        catch (Exception ex) 
        {
            System.out.println(ex);			
        }

    }//GEN-LAST:event_submitbuttonActionPerformed

    private void makefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makefieldActionPerformed

    private void colourfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colourfieldActionPerformed

    private void gngfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gngfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gngfieldActionPerformed

    private void ratefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratefieldActionPerformed

    private void monthmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OAddCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OAddCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OAddCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OAddCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OAddCycle(OID).setVisible(true);
            }
        });
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private java.awt.Button button7;
    private javax.swing.JTextField colourfield;
    private javax.swing.JTextField cycleidfield;
    private javax.swing.JComboBox<String> gngfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField makefield;
    private javax.swing.JLabel month;
    private javax.swing.JComboBox<String> monthmenu;
    private javax.swing.JTextField ratefield;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel year;
    private javax.swing.JTextField yopfield;
    // End of variables declaration//GEN-END:variables
}
